name: Release on version tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Release on NPM and GitHub
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - &checkout
        name: Check out Git repository
        uses: actions/checkout@v4

      - &setup
        name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          registry-url: 'https://registry.npmjs.org'

      - &install_deps
        name: Install dependencies
        shell: bash
        run: npm ci

      - name: Generate NPM package
        run: npm pack

      # This will also run the lint, test and build due to "prepare" and "prepublishOnly"
      - name: Publish to NPM
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Generate GitHub release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: ${{ contains(github.ref_name, '-') }}
          make_latest: ${{ !contains(github.ref_name, '-') }}
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            react-best-merge-refs-*.tgz
